version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "type/chore"
      - "area/ci"
    commit-message:
      prefix: "ci"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "type/chore"
    commit-message:
      prefix: "deps"
