global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: pushgateway
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]

  - job_name: subcog_mcp
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:9090"]

  - job_name: otel-collector
    static_configs:
      - targets: ["otel-collector:8889"]
